### ISSUE TITLE
Add support for icon tinting

### ISSUE THREAD

**Issue by olegosipenko** [scottyab/showhidepasswordedittext#11]
Using `DrawableCompat.wrap()` and `DrawableCompat.setTint()` it would be possible to tint icon on the fly

**Comment by scottyab** [comment]
I noticed a strange issue in the sample, once you use the tap either `javaTinting` or `xmlTinting` the other drawables in the view are also tinted. Maybe it's something the I guess it's an edge case that you'd want multi password fields on a page with different hide/show icon colours. But still wanted to flag encase you could see a fix. Tested on Android 4.2 and 5.0. 

![screenshot_22_01_2016_16_28](https://cloud.githubusercontent.com/assets/404105/12516411/3858fd08-c125-11e5-96cc-56e231cd5398.png)

**Comment by olegosipenko** [comment]
Strange
I tested it in my own app and there were no such issues
Waits for investigation

**Comment by ivannarino** [comment]
I think one solution here is to "mutate" the drawable so the drawable is not "recycled".

**Comment by olegosipenko** [comment]
@nex0s Lol. Completely forgot about this issue. Seems it was the root of the evil

**Comment by olegosipenko** [comment]
I added 'mutate' option to my commit to address this bug
