### ISSUE TITLE
Idea to improve "clickability" using dead drawablePadding space

### ISSUE THREAD

**Issue by guillermomuntaner** [scottyab/showhidepasswordedittext#16]
I've experimented some hard times clicking when the drawable is small. One simple but not elegant solution is to use bigger drawables or include empty margins in the drawable.

I think that checking only for inner X border is smart, but could be even better by adding some extra space. 
My first simple approach was to add an offset to the border. I used a relative value, but it could be done with an absolute value too:

```
private static double boundsXExtension = 1.5f; //It could be an xml attribute
// Then inside onTouchEvent()
 if ((leftToRight && (x >= (this.getRight() - (int)(boundsXExtension*bounds.width())))) ||
                    (!leftToRight &&  (x <= (this.getLeft() + (int)(boundsXExtension*bounds.width()))))){
```

Then i came up with a probably more elegant solution; which is taking advantage of the "**drawablePadding**" attribute. Its pixel value is accesible via `getCompoundDrawablePadding()`. This solution feels quite nice since it is adding some user value to an empty space that i guess everyone is using!

```
if ((leftToRight && (x >= (this.getRight() - (bounds.width()+getCompoundDrawablePadding())))) ||
                    (!leftToRight &&  (x <= (this.getLeft() + (bounds.width()+getCompoundDrawablePadding())))))
```

**Comment by scottyab** [comment]
Hey @guillermomuntaner thanks for suggesting this, I played with using `getCompoundDrawablePadding()` but it didn't give me the results I was looking for it was often very high and couldn't figure out why. So i've opted for an `additionalTouchTargetSize` attribute that you can pass a resource size to and that'll increase the clickability. This is in 0.7
