### ISSUE TITLE
android:inputType="number" is not working on Marshamallow

### ISSUE THREAD

**Issue by pawarlalit29** [scottyab/showhidepasswordedittext#18]
android:inputType="number" and android:digits="0123456789" is not working on Marshamallow

show some alphabetic keypad

**Comment by scottyab** [comment]
Thanks for reporting, i think this is related to #7

**Comment by scottyab** [comment]
Fixed in above commit and will be in 0.7  (also thanks for reporting this @pawarlalit29)

**Comment by pawarlalit29** [comment]
thanks dude..
i forgot to told you ,
but we manage that library code, some following changes in ShowHidePasswordEditText.java file in last week 
[ShowHidePasswordEditText.txt](https://github.com/scottyab/showhidepasswordedittext/files/341385/ShowHidePasswordEditText.txt)

**Comment by scottyab** [comment]
Hi, I'm not keen on the wrapping, catching and ignoring of the Exception within OnTouchEvent - but hey thanks for sharing
