### ISSUE TITLE
InputType gets changed when clicking the Show/Hide icon

### ISSUE THREAD

**Issue by ThomasSunderland** [scottyab/showhidepasswordedittext#7]
I have a password field with an input type of TYPE_CLASS_NUMBER which causes the numeric keyboard to be shown when given focus. If I click the Show/Hide icon then the keyboard unexpectedly changes to alphanumeric.

**Comment by scottyab** [comment]
This is likely down to recent enhancement in v0.3 to show the hint text as non-monospace. I'm setting the inputType as part of the `init()` the fix should be to get the current inputtype to preserve the xml defined inputtype.
