### ISSUE TITLE
EditText is not materialized on prelollipop

### ISSUE THREAD

**Issue by ivannarino** [scottyab/showhidepasswordedittext#8]
Using ShowHidePasswordEditText , the editText does not get the material design on pre-lollipop devices (Kitkat for example)

**Comment by stealthcopter** [comment]
Duplicated this bug running on emulator on API 19 (Kitkat)
![1](https://cloud.githubusercontent.com/assets/1211162/12451380/f9d0860a-bf80-11e5-8420-cbdefd3a411a.png)
![2](https://cloud.githubusercontent.com/assets/1211162/12451381/f9df20a2-bf80-11e5-8184-eabda7865923.png)
